### ISSUE TITLE
Connection refused bei  inverter

### ISSUE THREAD

**Issue by medicus07** [rlindner/node-red-contrib-sma-webconnect#2]
Hi there,

I tested your node, but I cannot establish any connection to my inverters.
Always I got the message: "Error: connect ECONNREFUSED 192.168.1.184:443"

I tested a Sunny Tripower 25.0 and a Sunny Island 6.0H.

**Comment by rlindner** [comment]
Hi, maybe that inverter doesn't support HTTPs as well (please see #1). Have you already tried to disable it?

**Comment by medicus07** [comment]
Hi, yes, I tried to use http request instead... it makes no difference. 

But in browser I can reach the inverter by http (configuration site).

**Comment by rlindner** [comment]
Can you post the error message you're getting with https disabled? The ":443" in the end of the message above implies an https connection.

**Comment by medicus07** [comment]
When I use http-request, NR terminates and makes a restart...no message in the debug node...

**Comment by gabrio79** [comment]
Hi, I have sunnytripower 9000TL and web server is not contained, so this addon does not running on my system. So I used MODBUS
![immagine](https://user-images.githubusercontent.com/65911264/87907891-bd9e5780-ca65-11ea-9981-cf68e98d2ad8.png)

**Comment by efiten** [comment]
> Hi, I have sunnytripower 9000TL and web server is not contained, so this addon does not running on my system. So I used MODBUS ![immagine](https://user-images.githubusercontent.com/65911264/87907891-bd9e5780-ca65-11ea-9981-cf68e98d2ad8.png)

Can you tell me how you did this? share your 'modbus' tile, and your N-R flow ?

**Comment by gabrio79** [comment]
> > Hi, I have sunnytripower 9000TL and web server is not contained, so this addon does not running on my system. So I used MODBUS ![immagine](https://user-images.githubusercontent.com/65911264/87907891-bd9e5780-ca65-11ea-9981-cf68e98d2ad8.png)
> 
> Can you tell me how you did this? share your 'modbus' tile, and your N-R flow ?

There are a collection of modbus nodes available for node-red which you will need to install.

Go the the menu and select manage Pallete and search for the node-red-contrib-modbus package.

**modbus-nodes-install**

There are 11 nodes in the package and they are grouped together in the Modbus section.modbus-nodes

Hello, attached my flow that now includes also energy (rename it .json before node red import feature)
[flows.txt](https://github.com/rlindner/node-red-contrib-sma-webconnect/files/8327846/flows.txt)

I'm also trying to use native modbus features in homeassistant, but I still have some problem, but I'm near the solution :-)


```
modbus:
  - name: SMA_inverter_11
    type: tcp
    host: 192.168.xx.xx    # use the ip address for your inverter as mentioned in the text
    port: 502 # use the port you saw in sunny explorer
    close_comm_on_error: true 
    delay: 5
    timeout: 5
    sensors:
      - name: "Potenza inverter 1"
        scan_interval: 5
        address: 30775
        slave: 3
        count: 2
        input_type: input
        device_class: "power"
        unit_of_measurement: W
        scale: 0.001
        precision: 2
        data_type: int32
```
